steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - --build-arg=VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - --build-arg=VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - --build-arg=VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
      - --build-arg=VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}
      - -t
      - asia-southeast1-docker.pkg.dev/cocoims/cocoims/frontend:latest
      - .
images:
  - asia-southeast1-docker.pkg.dev/cocoims/cocoims/frontend:latest
